import {
  Box,
  Button,
  Heading,
  Text,
  Stack,
  Container,
  HStack,
} from "@chakra-ui/react";
import Head from "next/head";
import Nav from "../components/Nav";
import React from "react";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box minH="100vh">
        <Box position="fixed" w="100%" backdropFilter="auto" backdropBlur="2px">
          <Nav />
        </Box>
        <Box pt="40px">
          <Container maxW={"6xl"}>
            <Stack
              as={Box}
              textAlign={"center"}
              spacing={{ base: 8, md: 14 }}
              py={{ base: 20, md: 36 }}
            >
              <Heading
                fontWeight={600}
                fontSize={{ base: "2xl", sm: "4xl", md: "6xl" }}
                lineHeight={"110%"}
              >
                Connect . Collaborate . Succeed <br />
                <Text as={"span"} color={"green.400"}>
                  with Assignment Dedo
                </Text>
              </Heading>
              <Text color={"gray.500"}>
                Assignment Dedo: The app that connects students, sharing
                knowledge and resources for easier success.
              </Text>
              <HStack
                direction={"column"}
                spacing={3}
                align={"center"}
                alignSelf={"center"}
                position={"relative"}
              >
                <Link href="/login">
                  <Button
                    colorScheme={"green"}
                    bg={"green.400"}
                    px={8}
                    _hover={{
                      bg: "green.500",
                    }}
                  >
                    Login
                  </Button>
                </Link>
                <Link href="/signup">
                  <Button
                    colorScheme={"green"}
                    variant="outline"
                    ml={6}
                    px={8}
                  >
                    Signup
                  </Button>
                </Link>
                
              </HStack>
            </Stack>
          </Container>
        </Box>
      </Box>
    </div>
  );
}
